name: 'tap_meltano'
version: '0.1.0'
require-dbt-version: [">=0.20.0", "<=1.0.0"]

config-version: 2

profile: local

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  tap_meltano:
    +full_refresh: true
    base:
      materialized: table
      
vars:
  schema: "{{ env_var('TARGET_POSTGRES_SCHEMA') }}" # the schema where the raw TapMeltano tables are located